name: CI Pipeline

on:
  push:
    branches:
      - [main]
  pull_request:
    branches:
      - [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configuração do JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build e testes com Maven
        run: ./mvnw clean verify
